/**
 * Insert-row form.
 *
 * The fields mirror the page's columns, minus the identity columns the database
 * fills itself. A blank field is left out of the INSERT so the database can
 * apply its default, and the literal `NULL` inserts an explicit SQL NULL. That
 * is the only way to express both without a per-field control, and the hint
 * says so.
 *
 * A `defaultValue` is shown but never sent: it is a raw SQL expression
 * (`now()`, `nextval(...)`), so quoting it as text would be wrong.
 */

import * as React from "react";

import { Button, Field, Input } from "@/components/ui/primitives";
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogFooter,
  DialogHeader,
} from "@/components/ui/overlays";
import {
  type ColumnMeta,
  NULL_VALUE,
  type Value,
  makeValue,
  toErrorPayload,
} from "@/lib/types";
import { shortType } from "@/lib/utils";

export interface InsertRowDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  columns: ColumnMeta[];
  table: string;
  /** Rejects with an `ErrorPayload` when the insert fails; the dialog stays open. */
  onSubmit: (values: Record<string, Value>) => Promise<void>;
}

function buildValues(
  columns: ColumnMeta[],
  text: Record<string, string>,
): Record<string, Value> {
  const values: Record<string, Value> = {};
  for (const column of columns) {
    const raw = (text[column.name] ?? "").trim();
    if (!raw) continue;
    values[column.name] = /^null$/i.test(raw)
      ? NULL_VALUE
      : makeValue(raw, column.logicalType);
  }
  return values;
}

export function InsertRowDialog({
  open,
  onOpenChange,
  columns,
  table,
  onSubmit,
}: InsertRowDialogProps): React.ReactElement {
  const [text, setText] = React.useState<Record<string, string>>({});
  const [error, setError] = React.useState<string | null>(null);
  const [busy, setBusy] = React.useState(false);

  // Identity columns are the database's job; offering them just invites errors.
  const fields = React.useMemo(
    () => columns.filter((column) => !column.isAutoIncrement),
    [columns],
  );
  const skipped = columns.length - fields.length;

  // Every open starts from a blank form rather than the previous attempt.
  React.useEffect(() => {
    if (!open) return;
    setText({});
    setError(null);
  }, [open]);

  const submit = async () => {
    setBusy(true);
    setError(null);
    try {
      await onSubmit(buildValues(fields, text));
      onOpenChange(false);
    } catch (caught) {
      setError(toErrorPayload(caught).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent size="lg">
        <DialogHeader
          title={`Insert into ${table}`}
          description="Leave a field blank to omit it and let the database apply its default. Type NULL for an explicit SQL NULL."
        />
        <DialogBody>
          {fields.length === 0 ? (
            <p className="text-[13px] text-muted">
              This relation has no columns to fill in — every column is generated by the
              database.
            </p>
          ) : (
            <form
              className="grid grid-cols-1 gap-x-4 gap-y-2.5 sm:grid-cols-2"
              onSubmit={(event) => {
                event.preventDefault();
                void submit();
              }}
            >
              {fields.map((column) => (
                <Field
                  key={column.name}
                  label={<span className="font-mono">{column.name}</span>}
                  hint={[
                    shortType(column.typeName),
                    column.isPrimaryKey ? "primary key" : null,
                    column.nullable ? "nullable" : "not null",
                  ]
                    .filter(Boolean)
                    .join(" · ")}
                >
                  <Input
                    value={text[column.name] ?? ""}
                    onChange={(event) =>
                      setText((prev) => ({ ...prev, [column.name]: event.target.value }))
                    }
                    placeholder={
                      column.defaultValue ? `default: ${column.defaultValue}` : "NULL"
                    }
                    spellCheck={false}
                    autoComplete="off"
                    className="h-7 font-mono text-[12px]"
                  />
                </Field>
              ))}
            </form>
          )}
          {skipped > 0 ? (
            <p className="mt-3 text-[11px] text-subtle">
              {skipped} auto-increment {skipped === 1 ? "column is" : "columns are"} left to the
              database.
            </p>
          ) : null}
          {error ? (
            <p className="mt-3 rounded-md border border-danger/30 bg-danger-soft px-2 py-1.5 text-[12px] text-danger">
              {error}
            </p>
          ) : null}
        </DialogBody>
        <DialogFooter>
          <Button type="button" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            type="button"
            variant="primary"
            loading={busy}
            disabled={fields.length === 0}
            onClick={() => void submit()}
          >
            Insert row
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
